### ISSUE TITLE
Potential out of bounds in neasyf_dim

### ISSUE THREAD

**Issue by d7919** [PlasmaFAIR/neasy-f#4]
If `dim_sizes` is passed by is `<= 0` then we end up creating an empty `local_values` array at
https://github.com/PlasmaFAIR/neasy-f/blob/afb2b2f7acaea14f6d2c8f6010091547bb2aa8b9/src/neasyf.f90#L828

This is then passed to `neasyf_type` but the `rank1` version of this (which will be the specific implementation used) assumes at least one value is the passed array:
https://github.com/PlasmaFAIR/neasy-f/blob/afb2b2f7acaea14f6d2c8f6010091547bb2aa8b9/src/neasyf.f90#L280-L284

Note the result of `neasyf_type` (`nf_type`) is not used in the method so one can simply remove this call to avoid the error here, but it suggests there may need to be some additional checking in `neasyf_dim` (or the existing checks moved earlier).

**Comment by ZedThree** [comment]
The out-of-bounds should (probably) now not happen because we don't accept zero-length arrays
